# Site settings
title:
  en: Kyiv Tours
  ua: Тури у Києв
  ru: Туры в Киев
email: inkyiv.info@gmail.com
description:
  en: Awesome description
  ua: 2-х и 3-х дневные индивидуальные туры в Киев для небольших групп с проживанием и обширной экскурсионной программой
  ru: 2-х и 3-х дневные индивидуальные туры в Киев для небольших групп с проживанием и обширной экскурсионной программой
index:
  en: indexen.html
  ua: indexua.html
  ru:
baseurl: ""
url: "http://inkyiv.com"
baseurl: ""
github_username: inkyiv

# Build settings
markdown: kramdown
