# Site settings
title:
  en: Kyiv Tours
  uk: Тури у Києв
  ru: Туры в Киев
email: inkyiv.info@gmail.com
description:
  en: Awesome description
  uk: 2-х и 3-х дневные индивидуальные туры в Киев для небольших групп с проживанием и обширной экскурсионной программой
  ru: 2-х и 3-х дневные индивидуальные туры в Киев для небольших групп с проживанием и обширной экскурсионной программой
mykeywords:
  en: Kyiv tours excursions
  uk: Київ тури екскурсії
  ru: "Киев, экскурсии, туры, индивидуальный подход, дешево"
index:
  en: indexen.html
  uk: indexua.html
  ru:
baseurl: ""
url: "http://inkyiv.com"
baseurl: ""
github_username: inkyiv

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap