# Site settings
title:
  en: Kyiv Tours
  ua: Тури в Києві
email: inkyiv.info@gmail.com
description:
  en: Awesome description
  ua: Опис
index:
  en:
  ua: indexua.html
baseurl: ""
url: "http://inkyiv.com"
baseurl: ""
github_username: inkyiv

# Build settings
markdown: kramdown
